x1 = float(input('Digite codernada x1:'))
x2 = float(input('Digite a cordenada de x2:'))
y1 = float(input('Digite codernada y1:'))
y2 = float(input('Digite a cordenade y2:'))
print(((x2 - x1)**2 + (y2 - y1)**2)**0.5)
